[package]
name = "saltyrtc-task-relayed-data"
version = "0.1.0"
authors = ["Danilo Bargen <danilo.bargen@threema.ch>"]

[dependencies]
clippy = { version = "*", optional = true }
failure = "0.1"
log = "0.3"
saltyrtc-client = { git = "https://github.com/saltyrtc/saltyrtc-client-rs.git", branch = "develop" }
tokio-core = "0.1"

[dev-dependencies]
env_logger = "0.5"
tokio-timer = "0.1"

[features]
msgpack-debugging = ["saltyrtc-client/msgpack-debugging"]
