version: 2
jobs:
  build:
    docker:
      - image: saltyrtc/circleci-image-rs:latest
    steps:
      - checkout

      # Load cargo target from cache if possible.
      # Multiple caches are used to increase the chance of a cache hit.
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ arch }}-{{ .Branch }}
            - v1-cargo-cache-{{ arch }}

      # Diagnostics
      - run:
          name: Show versions
          command: rustc --version && cargo --version

      # Certificates
      - run:
          name: Generate certificates
          command: /saltyrtc/certs/generate-cert.sh
      - run:
          name: Copy certificate
          command: cp /saltyrtc/certs/saltyrtc.der .

      # Start processes
      - run:
          name: Start SaltyRTC server
          command: nohup saltyrtc-server-launcher > server.pid

      # Build and test
      - run:
          name: Build
          command: cargo build
      - run:
          name: Test
          command: cargo test
      - run:
          name: Test (with flags)
          command: cargo build --features 'msgpack-debugging'
      - run:
          name: Audit
          command: cargo audit

      # Show server log
      - run:
          name: Print server log
          command: cat /saltyrtc/serverlog.txt

      # Save cache
      - save_cache:
          key: v1-cargo-cache-{{ arch }}-{{ .Branch }}
          paths:
            - target
            - /usr/local/cargo
      - save_cache:
          key: v1-cargo-cache-{{ arch }}
          paths:
            - target
            - /usr/local/cargo
